### ISSUE TITLE
Add cross-platform support

### ISSUE THREAD

**Issue by mauro-balades** [hrszpuk/rectx#14]
Dear Remy.

I can see that you only have support with UNIX-like systems. One good idea is to use cross-platform support from the start. I have seen lines of codes such as:

https://github.com/hrszpuk/rectx/blob/master/src/manager.rs#L82-L84

that won't work in a Windows Operating System (Since they use the `Inteligent\Path\main.rct`). One option is to use the rust's built-in function std::path::join function.

here are some examples: https://stackoverflow.com/questions/67816016/how-to-get-path-join-in-rust

Have a good day 👍🏽

**Comment by hrszpuk** [comment]
I want to keep this issue open until a pull request triggers it to close or it is closed manually after the feature has been implemented.
