### ISSUE TITLE
Check if source code has changed and if it has rebuild during `rectx run`

### ISSUE THREAD

**Issue by hrszpuk** [hrszpuk/rectx#48]
**Is your feature request related to a problem? Please describe.**
Rust's `cargo run` has the same feature I think it would be great if rectx could also do that. The solution would prevent occurrances where the user updates the source code but uses `rectx run` and the same output is generated prior to the updated source code. Essentially, this feature means user won't have to type `rectx build && rectx run` just `rectx run`. 

**Describe the solution you'd like**
Store a copy of the source code along side the project files (likely in a `.rectx` folder) which can then be used for the comparison. 

The copy is only made after the first `rectx build` or `rectx run`, and future `rectx run` calls after that will compare the source code to the code. If the source code is the same then rectx will just run the executable found in the build directory and update the copy. Otherwise it will rebuild the project, update the copy, and then run the executable.

The copy of the source will be hashed to save space on the user's disk. Settings in the `~/.rectx/config` will be able to be changed to disable hashing (stores the literal code instead).

**Additional context**
Thank you @RedCubeDev-ByteSpace and @khhs167 for helping come up with this solution.

**Comment by Khhs167** [comment]
professional. I like it.

**Comment by hrszpuk** [comment]
> Due to a lack of activity, this issue has been deemed stale. If this level of activity continues for a further 5 days this issues will be closed.

I'm so behind on project work the bot is starting to label issues has stale ;-;

**Comment by hrszpuk** [comment]
Created branch 👍🏼

**Comment by hrszpuk** [comment]
This issue suffers from the same problem as #62. If the source directory is not set within the config then rectx cannot hash the source directory. 

How I have to *actually* fix #62 😔.
